export const Fixtures = [
  {
    id: "1",
    team: "Kolek FC",
    venue: "Rafa Serenia",
    date: "05/04/25",
    time: "21:30",
    day: "Saturday",
  },
  {
    id: "2",
    team: "Kroni FC",
    venue: "Seriemas Sportplex",
    date: "12/04/25",
    time: "22:00",
    day: "Saturday",
  },
  {
    id: "3",
    team: "V Putra FC",
    venue: "Seriemas Sportplex",
    date: "18/04/25",
    time: "22:00",
    day: "Friday",
  },
  {
    id: "4",
    team: "Fighter FC",
    venue: "MAEPS Serdang",
    date: "24/04/25",
    time: "22:00",
    day: "Thursday",
  },
  {
    id: "5",
    team: "LeafTree FC",
    venue: "AG Sport Arena",
    date: "27/04/25",
    time: "20:00",
    day: "Sunday",
  },
  {
    id: "6",
    team: "Bukit Pelandok FC",
    venue: "Seriemas Sportplex",
    date: "10/05/25",
    time: "22:00",
    day: "Saturday",
  },
  {
    id: "7",
    team: "Team Apa FC",
    venue: "Seriemas Sportplex",
    date: "15/05/25",
    time: "22:00",
    day: "Thursday",
  },
  {
    id: "8",
    team: "M2J FC",
    venue: "Stadium Pancarona",
    date: "18/05/25",
    time: "20:00",
    day: "Sunday",
  },
  {
    id: "9",
    team: "Independent FC",
    venue: "Azman Hashim Sport Arena (UKM)",
    date: "22/05/25",
    time: "22:00",
    day: "Thursday",
  },
  {
    id: "10",
    team: "Ganador FC",
    venue: "Highbury Arena",
    date: "30/05/25",
    time: "22:00",
    day: "Friday",
  },
  {
    id: "11",
    team: "Ben Davies FC",
    venue: "Rafa Serenia",
    date: "05/06/25",
    time: "21:00",
    day: "Thursday",
  },
  {
    id: "12",
    team: "Training Match",
    venue: "Rafa Serenia",
    date: "08/06/25",
    time: "21:00",
    day: "Sunday",
  },
  {
    id: "13",
    team: "HK FC",
    venue: "Azman Hashim Sport Arena (UKM)",
    date: "11/06/25",
    time: "22:00",
    day: "Wednesday",
  },
  {
    id: "14",
    team: "Zuwan FC",
    venue: "Azman Hashim Sport Arena (UKM)",
    date: "15/06/25",
    time: "22:00",
    day: "Sunday",
  },
  {
    id: "15",
    team: "Anak Soleh FC",
    venue: "Seriemas Sportplex",
    date: "19/06/25",
    time: "22:00",
    day: "Thursday",
  },
];
