export const Players = [
  {
    id: "1",
    fullname: "Faizul Hasnan B. Abu Hassan",
    callname: "FAIZUL",
    age: 32,
    jersey: 73,
    position: "Midfielder",
    attribute: "Ball Control",
    level: 90,
    attr: "Passing",
    img: require("@/assets/images/Faizul.png"),
    appearances: 9,
    goals: 0,
    wins: 7,
    losses: 2,
  },
  {
    id: "2",
    fullname: "Mohammad Shahrizal B. Zoljefry",
    callname: "RIZAL",
    age: 32,
    jersey: 9,
    position: "Forward",
    attribute: "Finishing",
    level: 90,
    attr: "Shooting",
    img: require("@/assets/images/Rizal.png"),
    appearances: 9,
    goals: 0,
    wins: 7,
    losses: 2,
  },
  {
    id: "3",
    fullname: "Mohd Syazwan B. Mohd Nooh",
    callname: "WAN",
    age: 38,
    jersey: 14,
    position: "Defender",
    attribute: "Tackling",
    level: 90,
    attr: "Man-Marking",
    img: require("@/assets/images/Faizul.png"),
    appearances: 9,
    goals: 0,
    wins: 7,
    losses: 2,
  },
  {
    id: "4",
    fullname: "Muhammad Syakir Aiman B. Shahrull Adli",
    callname: "KIRMAN",
    age: 29,
    jersey: 17,
    position: "Defender",
    attribute: "Passing",
    level: 90,
    attr: "Man-Marking",
    img: require("@/assets/images/Syakir.png"),
    appearances: 9,
    goals: 0,
    wins: 7,
    losses: 2,
  },
  {
    id: "5",
    fullname: "Muhammad Rashidi B. Azmi",
    callname: "SHIDI",
    age: 38,
    jersey: 9,
    position: "Forward",
    attribute: "Speed",
    level: 90,
    attr: "Agility",
    img: require("@/assets/images/Shidi.png"),
    appearances: 9,
    goals: 0,
    wins: 7,
    losses: 2,
  },
  {
    id: "6",
    fullname: "Mohd Rukhaire B. Abdul Rahim",
    callname: "KHAIRE",
    age: 46,
    jersey: 12,
    position: "Midfielder",
    attribute: "Dribbling",
    level: 90,
    attr: "Distribution",
    img: require("@/assets/images/Khaire.png"),
    appearances: 9,
    goals: 0,
    wins: 7,
    losses: 2,
  },
];
